[package]
name = "snekrs"
version = "0.2.0"
edition = "2021"
authors = ["Logesh kumar <logeshgcp@gmail.com>"]
description = "A fun and quirky terminal-based snake game written in Rust ğŸ"
license = "MIT"
repository = "https://github.com/logesh-kumar/snekrs"
keywords = ["game", "snake", "terminal", "arcade", "snek"]
categories = ["games", "command-line-utilities"]
readme = "README.md"

[dependencies]
crossterm = "0.28.1"
rand = "0.8.5"
